### PR TITLE
Upgade dependencies

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
#28 will fix the build :smile:

**Comment by SummerWish** [comment]
Updated all dependencies :-)
Still thank you for your PR!

**Comment by PeterDaveHello** [comment]
lol

**Comment by Martii** [comment]
@SummerWish 
Failure in dep upgrade with SunOS systems... details at OpenUserJs/OpenUserJS.org#631 and OpenUserJs/OpenUserJS.org#632 ... we have downgraded on production/dev and all is well so this should probably be retested in your package. Thanks. :)

**Pull request closed without merging**
