### PR TITLE
bump version to v0.1.4

### PR DESCRIPTION
**Pull request by PeterDaveHello**
@SummerWish, let's bump and publish it! Thanks :smile:

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@SummerWish When will you push to npm?

**Comment by SummerWish** [comment]
I need some minute to pull & publish due to Chinese firewall :-)

**Comment by PeterDaveHello** [comment]
Okay, I can't wait for the new version!

**Comment by SummerWish** [comment]
Done 😄

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by PeterDaveHello** [comment]
Still v0.1.3 here, https://www.npmjs.com/package/express-minify, how long will it update after you pushed it?

**Comment by PeterDaveHello** [comment]
Nerver mind, `npm install` installed v0.1.4

**Comment by SummerWish** [comment]
Mine is 0.1.4 :-) a refresh? or cache or CDN delay..?

**Comment by SummerWish** [comment]
LOL

**Comment by PeterDaveHello** [comment]
The webpage also updated.

**Pull request merged**
